name: Fudan Daily

on:
  schedule:
    - cron: '0 2,6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait
        uses: 1itachi/sleep-random@v1.0.0
        with:
          minutes: '2'
          random: 'true'
      - id: Roll-dice
        run: echo "PROCEED=$((RANDOM%2))" >> $GITHUB_ENV
        shell: bash
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+00:00"
      - if: ${{ steps.current-time.outputs.hour }} > 4
        run: echo "PROCEED=1" >> $GITHUB_ENV
        shell: bash
      - if: env.PROCEED == '0'
        name: Cancelling
        uses: andymckay/cancel-action@0.2
      - if: env.PROCEED == '0'
        name: Waiting for cancellation
        run: sleep 60
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Prepare environment
        run: pip install bs4 lxml requests pyyaml pillow tensorflow-cpu opencv-python
      - name: Run app
        run: python toyy.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
